/// <reference types="vite/client" />


type Tree = {
  id: number;
  recordNo: string;
  treeTypeID: number;
  treeSpeciesID: number;
  age: string;
  size: string;
  ycOne: string;
  storyText: string;
  district: string;
  neighborhood: string;
  street: string;
  isBook: number;
  cultural: string;
  dimensional: string;
  peakDiameter: string;
  latitude: number;
  longitude: number;
  title_tr: string;
  title_lt: string;
  treeImage: string;
  isCover: number;
}

type TreeRecord = {
  id: number;
  qrCode: string;
  mapImage: string;
  tomographyImage: string;
  detectionNo: string;
  inventoryNo: string;
  recordNo: string;
  protectID: number;
  treeTypeID: number;
  treeSpeciesID: number;
  sheetNo: string;
  islandNo: string;
  parcelNo: string;
  ed50Y: string;
  ed50X: string;
  xCoordinate: string;
  yCoordinate: string;
  zCoordinate: string;
  localName: string;
  ownership: string;
  location: string;
  locationType: string;
  locationTypeSmall: string;
  usage: string;
  age: string;
  imageFeature: string;
  uniqueFeature: string;
  featureText: string;
  district: string;
  neighborhood: string;
  street: string;
  address: string;
  latitude: string;
  longitude: string;
  look: number;
  slope: string;
  slopeText: string;
  soilLevelPerimeter: string;
  ycOne: string;
  ycTwo: string | null;
  ycThree: string | null;
  ycFour: string | null;
  ycFive: string | null;
  yceOne: string;
  yceTwo: string | null;
  yceThree: string | null;
  yceFour: string | null;
  yceFive: string | null;
  size: string;
  aValue: string;
  bValue: string;
  cValue: string;
  dValue: string;
  peakDiameter: string;
  peakProjection: string;
  generalHatibus: number;
  bifurcation: string;
  curvatureDegree: string;
  numberOfHolesRots: string;
  hollowRottenPlace: string;
  hollowRottenRatio: string;
  urSwellingNumber: string;
  urSwellingLocation: string;
  urSwellingRatio: string;
  peakCondition: string;
  healthStatus: string;
  healthStatusText: string;
  socialCulturalText: string;
  storyText: string;
  peakSurfaceArea: string;
  weight: string;
  cariesRate: string;
  personalHealthStatus: string;
  riskStatus: number;
  diseased: string;
  requirementForIntervention: string;
  currentStatus: string;
  dimensional: string;
  cultural: string;
  contribution: string;
  technicalAction: string;
  registrationStatus: string | null;
  registrationName: string | null;
  registrationNumber: string | null;
  registrationDecisionNo: string | null;
  registrationDate: string | null;
  registrationRecordDate: string | null;
  municipalityName: string | null;
  municipalityRegistration: string | null;
  personalNameOne: string;
  personalNameTwo: string;
  personalNameThree: string;
  personalTitleOne: string;
  personalTitleTwo: string;
  personalTitleThree: string;
  isActive: number;
  isBook: number;
  created_at: string;
  updated_at: string;
  isCover: number;
  image: string;
  title_tr: string;
  title_lt: string;
  typeName: string;
  protectTitle: string;
  text: string;
  link: string;
};


